export default[
    {
        "tagline":"Сказочное заморское яство",
        "product_name":"Нямушка",
        "id":"1",
        "with_what":"с фуа-гра",
        "dose":"10 порций",
        "present":"мышь в подарок",
        "customer_satisfied":" ",
        "weight":"0,5",
        "product_footer1":"Чего сидишь? Порадуй коте, ",
        "product_footer2":"Отличное лакомство с фуа-гра",
        "product_footer3":"Печалька, с фуа-гра закончился.",
        "product_selected":false,
        "presence":true,
        "buy_referenced": true
    },
    {
        "tagline":"Сказочное заморское яство",
        "product_name":"Нямушка",
        "id":"2",
        "with_what":"с рыбой",
        "dose":"40 порций",
        "present":"2 мыши в подарок",
        "customer_satisfied":" ",
        "weight":"2",
        "product_footer1":"Чего сидишь? Порадуй коте, ",
        "product_footer2":"Головы щучьи с чесноком, да свежайшая семгушка",
        "product_footer3":"Печалька, с рыбой закончился",
        "product_selected":false,
        "presence":true,
        "buy_referenced": true
    },
    {
        "tagline":"Сказочное заморское яство",
        "product_name":"Нямушка",
        "id":"3",
        "with_what":"с курой",
        "dose":"100 порций",
        "present":"5 мышей в подарок",
        "customer_satisfied":"заказчик доволен",
        "weight":"5",
        "product_footer1":"Чего сидишь? Порадуй коте, ",
        "product_footer2":"Нежная мякоть курочки",
        "product_footer3":"Печалька, с курой закончились",
        "product_selected":false,
        "presence":false,
        "buy_referenced": true
    }
]